# Generated by Django 5.2.8 on 2025-11-27 16:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Рақами курс')),
                ('name', models.CharField(max_length=100, verbose_name='Номи курс')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсҳо',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Номи семестр')),
                ('start_date', models.DateField(verbose_name='Санаи оғоз')),
                ('end_date', models.DateField(verbose_name='Санаи анҷом')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаъол')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестрҳо',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('dean', 'Декан'), ('admin', 'Админ'), ('zamdekan', 'Замдекан'), ('teacher', 'Омӯзгор')], max_length=20, verbose_name='Нақш')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Номи пурра')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Сурат')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Корбар',
                'verbose_name_plural': 'Корбарон',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Номи гурӯҳ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сана')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='common.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Гурӯҳ',
                'verbose_name_plural': 'Гурӯҳҳо',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='Рақами донишҷӯӣ')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ном')),
                ('last_name', models.CharField(max_length=100, verbose_name='Насаб')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Номи падар')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Сурат')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Санаи қабул')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='GPA')),
                ('contract_status', models.CharField(choices=[('paid', 'Пардохт'), ('debt', 'Қарз')], default='paid', max_length=20, verbose_name='Ҳолати шартнома')),
                ('is_active', models.BooleanField(default=True, verbose_name='Фаъол')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.course', verbose_name='Курс')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='common.group', verbose_name='Гурӯҳ')),
            ],
            options={
                'verbose_name': 'Донишҷӯ',
                'verbose_name_plural': 'Донишҷӯён',
                'ordering': ['group', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Матн')),
                ('comment_type', models.CharField(choices=[('positive', 'Мусбат'), ('negative', 'Манфӣ'), ('neutral', 'Хунук')], default='neutral', max_length=20, verbose_name='Навъ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сана')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Муаллиф')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='common.student', verbose_name='Донишҷӯ')),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Комментҳо',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Номи фан')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Коди фан')),
                ('hours_per_week', models.IntegerField(default=3, verbose_name='Соатҳо дар ҳафта')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='common.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Фан',
                'verbose_name_plural': 'Фанҳо',
                'ordering': ['course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_grade', models.BooleanField(default=True, verbose_name='Ҳуқуқи баҳогузорӣ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.group', verbose_name='Гурӯҳ')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.semester', verbose_name='Семестр')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.subject', verbose_name='Фан')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Омӯзгор')),
            ],
            options={
                'verbose_name': 'Таъинот',
                'verbose_name_plural': 'Таъинотҳо',
                'unique_together': {('teacher', 'group', 'subject', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Душанбе'), (1, 'Сешанбе'), (2, 'Чоршанбе'), (3, 'Панҷшанбе'), (4, 'Ҷумъа'), (5, 'Шанбе')], verbose_name='Рӯзи ҳафта')),
                ('start_time', models.TimeField(verbose_name='Вақти оғоз')),
                ('end_time', models.TimeField(verbose_name='Вақти анҷом')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Толор')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='common.teacherassignment', verbose_name='Таъинот')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписанияҳо',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CurrentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Сана')),
                ('present_count', models.IntegerField(default=0, verbose_name='Ҳозирон')),
                ('total_students', models.IntegerField(default=0, verbose_name='Ҷамъи донишҷӯён')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Дарси ҷорӣ',
                'verbose_name_plural': 'Дарсҳои ҷорӣ',
                'unique_together': {('schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Сана')),
                ('grade', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Баҳо')),
                ('attendance', models.BooleanField(default=False, verbose_name='Ҳозиршавӣ')),
                ('attendance_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Баллҳои ҳозиршавӣ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Навсозӣ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='common.student', verbose_name='Донишҷӯ')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.teacherassignment', verbose_name='Таъинот')),
            ],
            options={
                'verbose_name': 'Ёддошти журнал',
                'verbose_name_plural': 'Ёддоштҳои журнал',
                'ordering': ['-date'],
                'unique_together': {('student', 'teacher_assignment', 'date')},
            },
        ),
    ]
